name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Construção e push da imagem Docker
      - name: Construção da Imagem Docker
        uses: docker/build-push-action@v3
        with:
          context: /home/victor/kube-news/src
          file: Dockerfile      # relativo ao context
          push: true
          tags: |
            fabriciovoronez/live-kube-news:v1
            fabriciovoronez/live-kube-news:latest
