name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3. Construção e Push da Imagem Docker
      - name: Construção e Push da Imagem Docker
        uses: docker/build-push-action@v3
        with:
          context: ./src           # contexto agora é src
          file: ./src/Dockerfile   # caminho relativo ao repo
          push: true
          tags: |
            fabriciovoronez/live-kube-news:v1
            fabriciovoronez/live-kube-news:latest
